### ISSUE TITLE
出错了唉

### ISSUE THREAD

**Issue by char1eslu** [JasonkayZK/docker-repo#1]
![image](https://user-images.githubusercontent.com/20885743/132112501-e59f5c32-4314-4c00-8432-c60567218b29.png)

**Comment by JasonkayZK** [comment]
邮件和密码确定是对的吗？2FA有木有关闭

**Comment by char1eslu** [comment]
> 邮件和密码确定是对的吗？2FA有木有关闭

<img width="819" alt="image" src="https://user-images.githubusercontent.com/20885743/132112997-a5cc23fb-36f1-4cab-a926-e89157c19f79.png">
对的呀，2FA也关了呢

**Comment by JasonkayZK** [comment]
啊…，这；
我也不知道哇，我这边没什么问题；
这个镜像也不是我的；
你在这个下面留言试试？
https://www.appinn.com/epicgames-claimer-docker/

**Comment by char1eslu** [comment]
> 啊…，这；
> 我也不知道哇，我这边没什么问题；
> 这个镜像也不是我的；
> 你在这个下面留言试试？
> https://www.appinn.com/epicgames-claimer-docker/

好哇，谢谢啦
